
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project2-eks-cluster
  region: us-east-1

vpc:
  id: null
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single
  manageSharedNodeSecurityGroupRules: true


nodeGroups:
  - name: ng1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 30

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
      roleName: AmazonEKS_EBS_CSI_DriverRole
      roleOnly: false
      
      

addons:
  - name: aws-ebs-csi-driver
    version: latest
